import type { SiteLabels } from "@/types/cms";

export const DEFAULT_LABELS: SiteLabels = {
  breadcrumbs: {
    company: "Company",
    contact: "Contact",
    products: "Products",
    solutions: "Solutions",
    getInTouch: "Get in touch",
    ourSolutions: "Our Solutions",
  },
  home: {
    readMore: "Read More",
    viewProduct: "View Product",
    fullCatalogue: "Full Products Catalogue",
    machinesEyebrow: "Machines",
    clientsEyebrow: "Clients",
    heroImageAlt: "Commercial laundry equipment",
  },
  solutions: {
    learnMore: "Learn more",
    benefitsHeading: "Key Benefits",
    partnerTitle: "Partner With Us",
    partnerText:
      "Speak with our solutions team for a tailored proposal — equipment supply, consultancy, layout design and installation support across India.",
    contactCta: "Contact Us",
    keyPointsHeading: "Key Points",
  },
  products: {
    viewDetails: "View details",
    enquireTitle: "Enquire About This Product",
    enquireText: "Contact Laundrex for specifications, pricing and installation support across India.",
    enquireCta: "Contact Us",
    specsHeading: "Specifications",
    featuresHeading: "Key Features",
  },
  contact: {
    getInTouchTitle: "Get in Touch",
    getInTouchSubtitle: "We're here to help with equipment, consultancy, and service.",
    sendMessageTitle: "Send a Message",
    sendMessageSubtitle: "Fill out the form and we'll respond promptly.",
    serviceCentresTitle: "Service Centres",
    formName: "Name *",
    formEmail: "Email *",
    formPhone: "Phone",
    formPhonePlaceholder: "+91",
    formCompany: "Company",
    formMessage: "Message *",
    formSubmit: "Send Message",
    formSubmitting: "Sending...",
    formSuccess: "Thank you. We will respond within one business day.",
    formError: "Something went wrong. Please try again.",
  },
  newsletter: {
    namePlaceholder: "Your name",
    emailPlaceholder: "Your email",
    subscribe: "Subscribe",
    subscribing: "Subscribing...",
    successTitle: "Thank you for subscribing!",
    successText: "You'll receive our latest updates soon.",
    errorName: "Please enter your name.",
    errorEmail: "Please enter a valid email address.",
    errorGeneric: "Something went wrong. Please try again.",
  },
  whatsapp: {
    ariaLabel: "Chat on WhatsApp",
    modalTitle: "Chat on WhatsApp",
    modalSubtitle: "Enter your details to message us directly",
    nameLabel: "Full Name *",
    namePlaceholder: "Your full name",
    phoneLabel: "Phone Number *",
    phonePlaceholder: "+91 98765 43210",
    phoneError: "Enter a valid Indian mobile number (+91, 10 digits).",
    inquiryLabel: "Inquiry type",
    inquiryOptional: "(optional)",
    submit: "Start Chat on WhatsApp",
    submitting: "Opening WhatsApp...",
    inquiryOptions: [
      { value: "", label: "General inquiry" },
      { value: "Laundry machines & equipment", label: "Laundry machines & equipment" },
      { value: "Dry cleaning solutions", label: "Dry cleaning solutions" },
      { value: "Consultancy & setup", label: "Consultancy & setup" },
      { value: "Service & maintenance", label: "Service & maintenance" },
    ],
  },
  meta: {
    about: "About Us",
    contact: "Contact",
    products: "Products",
    solutions: "Solutions",
    news: "News & Media",
    sustainability: "Sustainability",
    financialPlanning: "Financial Planning",
    reweave360: "ReWeave 360",
    team: "Our Team",
    investors: "Investors",
    blog: "News & Insights",
    terms: "Terms of Service",
    privacy: "Privacy Policy",
    codeOfConduct: "Code of Conduct",
  },
};
