import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const brands = Array.from({ length: 18 }, (_, i) => ({
  id: `b${i + 1}`,
  name: `Partner ${i + 1}`,
  image: `/images/brands/${i + 1}.jpg`,
}));

const cms = {
  settings: {
    siteName: "Laundrex",
    companyLegalName: "Laundrex Laundry Systems Pvt. Ltd.",
    tagline: "",
    logo: "/images/logo.png",
    favicon: "/images/favicon-32.png",
    whatsappNumber: "917358258229",
    whatsappMessage: "Hello, I would like to know more about Laundrex.",
    whatsappGreetingTemplate:
      "Hi, I'm {name}. My number is {phone}. I'd like to inquire about your laundry machines/services.",
    liveChatEmbed: "",
    contactEmail: "hello@quickclean.co.in",
    contactPhone: "+91 98213 54872 / +91 86899 11455",
    addressLine1: "GSC Towers, 4th Floor, Sector 30",
    addressLine2: "",
    city: "Gurugram, Haryana 122001",
    country: "India",
    linkedin: "https://linkedin.com/company/quickclean",
    twitter: "https://twitter.com/quickclean",
    facebook: "https://facebook.com/quickclean",
    businessHours: "Mon - Sat: 9:00 - 19:00",
    headerCtaText: "Contact Us",
    headerCtaLink: "/contact-us",
  },
  navigation: [
    { label: "Home", href: "/" },
    {
      label: "Company",
      href: "/about-us",
      children: [
        { label: "About Us", href: "/about-us" },
        { label: "Our Team", href: "/our-team" },
        { label: "Sustainability", href: "/sustainability" },
        { label: "Our Investors", href: "/our-investors" },
        { label: "Financial Planning", href: "/financial-planning" },
      ],
    },
    {
      label: "Our Solutions",
      href: "/build-own-and-operate",
      children: [
        { label: "Build Own & Operate", href: "/build-own-and-operate" },
        { label: "Turnkey Project", href: "/turnkey-project" },
        { label: "Linen Rental", href: "/linen-rental" },
        { label: "Equipment on Lease", href: "/equipment-on-lease" },
      ],
    },
    { label: "Reweave 360", href: "/reweave-360" },
    { label: "Contact Us", href: "/contact-us" },
  ],
  home: {
    heroTitle: "Your Trusted Partner",
    heroTitleLine2: "In Sustainable Laundry Solutions",
    heroSubtitle: "",
    heroCtaText: "Our Solutions",
    heroCtaLink: "/build-own-and-operate",
    heroSecondaryCtaText: "Contact Us",
    heroSecondaryCtaLink: "/contact-us",
    heroImage: "/images/hero.jpg",
    stats: [
      { value: 110, suffix: "+", label: "On-Premise Laundry Sites" },
      { value: 1500, suffix: "+", label: "Skilled employees" },
      { value: 38, suffix: "+", label: "Cities Across India" },
    ],
    linenWashedLabel: "Linen Washed / Day",
    linenWashedValue: 100,
    linenWashedSuffix: "K",
    linenWashedUnit: "kg linen handled",
    waterComparison: {
      title: "Water Usage",
      industryLabel: "Water Used by Industry Standard (24 L/kg)",
      industryDisplayValue: 2400000,
      industryValue: 24,
      industryUnit: " L/kg",
      qcLabel: "Water Used by QC (8 L/kg)",
      qcDisplayValue: 800000,
      qcValue: 8,
      qcUnit: " L/kg",
      monthlySavedLabel: "Monthly Water Saved",
      monthlySaved: 27200000,
      yearlySavedLabel: "Yearly Water Saved",
      yearlySaved: 268800000,
    },
    solutionsTitle: "Our Solutions",
    solutionsSubtitle:
      "Sustainable laundry solutions that save water, cut energy use, and boost operational efficiency.",
    sustainabilityTitle: "",
    sustainabilityStats: [
      { value: 457, suffix: "+", label: "million liters of water saved" },
      { value: 60, suffix: "M kg", label: "carbon emissions reduced" },
    ],
    sustainabilityImpactTitle: "",
    founderTitle: "From the Founder's Desk",
    founderMessage:
      "Laundrex started as a dream I carried with me. Today it has a home, a family, and a heartbeat of its own. I'm just grateful— for our team, for the people who believed in us, and for every challenge that made us better. This isn't just laundry; it's hope, belief, and the fire to keep building. Here's to the next chapter.",
    founderName: "Anshul Gupta",
    founderRole: "CEO",
    founderImage: "/images/founder.jpg",
    sinceYear: "2010",
    videoTitle: "Since 2010",
    videoUrl: "https://www.youtube.com/embed/R4_bNukULNE",
    videoThumbnail: "/images/hero.jpg",
    brandsTitle: "Preferred Laundry Partner of<br /><strong>Leading Brands</strong>",
    clientsTitle: "What Our Partners Say",
    newsTitle: "News",
    newsSubtitle: "Subscribe for the latest news. Stay updated on the latest trends.",
    newsletterTitle: "Subscribe for the latest news",
    newsletterSubtitle: "Stay updated on the latest trends.",
  },
  solutions: [
    {
      id: "boo",
      slug: "build-own-and-operate",
      title: "Build Own & Operate",
      shortDescription:
        "We design, own, operate your laundry—effortless setup, zero investment, predictable efficiency.",
      description:
        "Laundrex's Build, Own & Operate (BOO) model delivers a complete, on-premise laundry that is designed, installed, owned, and fully operated by us—at zero capex to you. Your property receives a high-performance laundry inside the premises, and you simply pay a transparent per-kg processing price based on actual usage.\n\nWe build. We own. We operate.\n\nWith 110+ on-premise laundries, 3,000+ machines installed, and 70,000+ kg processed per day across India, Quick Clean brings unmatched reliability, sustainability, and operational consistency to hotels and hospitals nationwide.",
      image: "/images/hero.jpg",
      features: [
        "Zero Capital Investment",
        "End-to-End Operational Ease",
        "Consistent Hygiene & Quality",
        "Sustainable, High-Efficiency Operations",
        "Predictable, Transparent Billing",
      ],
      ctaText: "Get Started",
      ctaLink: "/contact-us",
      priceFromINR: 0,
      priceFromUSD: 0,
      priceFromEUR: 0,
      priceFromAED: 0,
    },
    {
      id: "turnkey",
      slug: "turnkey-project",
      title: "Turnkey Project",
      shortDescription:
        "Complete laundry system handled—from design to staff training, installation, and seamless launch.",
      description:
        "Our turnkey approach delivers a production-ready on-premise commercial laundry from concept to first load. Engineering teams design layouts optimised for workflow, hygiene zoning, and energy efficiency.",
      image: "/images/hero.jpg",
      features: [
        "Site assessment and engineering design",
        "OEM equipment procurement and installation",
        "Utility planning — steam, water, drainage, electrical",
        "Commissioning, staff training, and SOP documentation",
      ],
      ctaText: "Contact Us",
      ctaLink: "/contact-us",
      priceFromINR: 0,
      priceFromUSD: 0,
      priceFromEUR: 0,
      priceFromAED: 0,
    },
    {
      id: "linen",
      slug: "linen-rental",
      title: "Linen Rental",
      shortDescription:
        "Receive hygienic, professionally cleaned linens on schedule, freeing your resources for core operations.",
      description:
        "Outsource your institutional linen lifecycle to Laundrex. We supply quality-assured textiles, collect soiled inventory, process through certified commercial laundries, and deliver fresh stock on agreed schedules.",
      image: "/images/hero.jpg",
      features: [
        "Full linen inventory management",
        "Scheduled collection and delivery cycles",
        "Hygiene-certified processing",
        "Flexible volume scaling",
      ],
      ctaText: "Contact Us",
      ctaLink: "/contact-us",
      priceFromINR: 0,
      priceFromUSD: 0,
      priceFromEUR: 0,
      priceFromAED: 0,
    },
    {
      id: "lease",
      slug: "equipment-on-lease",
      title: "Equipment on Lease",
      shortDescription:
        "Lease high‑capacity eco‑efficient laundry machines with flexible terms—no ownership burdens.",
      description:
        "Access industrial-grade washer-extractors, tumble dryers, flatwork ironers, and finishing lines without large capital outlays. Lease structures include maintenance packages and upgrade options.",
      image: "/images/hero.jpg",
      features: [
        "Flexible lease tenures",
        "Comprehensive maintenance cover",
        "Upgrade paths to newer models",
        "Tax-efficient structuring",
      ],
      ctaText: "Contact Us",
      ctaLink: "/contact-us",
      priceFromINR: 0,
      priceFromUSD: 0,
      priceFromEUR: 0,
      priceFromAED: 0,
    },
  ],
  testimonials: [
    {
      id: "t1",
      quote:
        "Laundrex's BOO model made our laundry setup effortless and cost-free. Their team manages everything with great efficiency, and the results have been consistently excellent.",
      author: "Nitin Sharma",
      company: "",
      image: "/images/testimonial-nitin.jpg",
      rating: 5,
    },
  ],
  brands,
  blogCategories: ["Uncategorized", "Linen hygiene"],
  blog: [
    {
      id: "blog1",
      slug: "why-commercial-laundry-is-still-a-maturing-manufacturing-category-in-india",
      title: "Why Commercial Laundry Is Still a Maturing Manufacturing Category in India",
      excerpt:
        "India has made strong progress in manufacturing across many sectors. However, when it comes to commercial laundry machines for hotels and large institutions, there is still a noticeable gap between locally manufactured systems and globally proven commercial technology.",
      content:
        "India has made strong progress in manufacturing across many sectors. However, when it comes to commercial laundry machines for hotels and large institutions, there is still a noticeable gap between locally manufactured systems and globally proven commercial technology.\n\nThis is not a question of intent or affordability. It is a question of performance at scale.\n\nCommercial laundry environments are demanding. Machines operate continuously, handle heavy loads, and are expected to deliver consistent results with minimal downtime. In these conditions, small design and control limitations quickly translate into higher operating costs and reduced reliability.\n\nAt first glance, many locally manufactured machines appear adequate. They perform basic wash and dry functions and may work well in low-volume or intermittent-use settings.\n\nHowever, commercial laundry performance is measured over thousands of cycles, not initial operation. Differences in motor control, extraction capability, water management, automation, and monitoring become increasingly visible as volume and usage intensity increase.\n\nIn real-world operations, these gaps compound quickly. Lower extraction leaves linen wetter, increasing drying time and energy consumption. Manual or less precise dosing raises water and chemical usage while reducing wash consistency. Limited automation and diagnostics delay issue detection and increase operational strain.\n\nOver time, this results in higher utility costs, reduced daily capacity, faster linen wear, and greater vulnerability during peak demand.\n\nThis is not a permanent assessment. Indian manufacturing capability is evolving rapidly, and progress is clearly visible.\n\nBut today, for high-volume, mission-critical commercial laundry operations, consistency, efficiency, and uptime still favor globally proven systems.\n\nThat is why many hotels and large institutions continue to rely on them.",
      category: "Uncategorized",
      image: "/images/blog-manufacturing.jpg",
      date: "2025-09-08",
    },
    {
      id: "blog2",
      slug: "why-linen-management-directly-impacts-hotel-revenue",
      title: "Why Linen Management Directly Impacts Hotel Revenue",
      excerpt:
        "In most hotels, linen management is treated as a back-of-house function. Necessary, but operational. Something handled quietly behind the scenes.",
      content:
        "In most hotels, linen management is treated as a back-of-house function. Necessary, but operational. Something handled quietly behind the scenes.\n\nBut linen quality, availability, and turnaround time directly shape guest experience — and guest experience directly shapes revenue.",
      category: "Linen hygiene",
      image: "/images/blog-hotel-revenue.jpg",
      date: "2025-09-05",
    },
    {
      id: "blog3",
      slug: "the-silent-killer-in-hospital-linen",
      title: "The Silent Killer in Hospital Linen",
      excerpt:
        "India's most trusted hospitals are known for spotless corridors, advanced ICUs, and cutting-edge medical technology.",
      content:
        "India's most trusted hospitals are known for spotless corridors, advanced ICUs, and cutting-edge medical technology.\n\nYet behind the scenes, hospital linen hygiene remains one of the most underestimated infection risks in healthcare operations.",
      category: "Linen hygiene",
      image: "/images/blog-hospital-linen.jpg",
      date: "2025-08-29",
    },
    {
      id: "blog4",
      slug: "the-hidden-cost-of-outdated-laundry-systems",
      title: "The Hidden Cost of Outdated Laundry Systems — And Here's the Fix",
      excerpt:
        "Every day, hotels and hospitals lose millions without even noticing. The culprit sits quietly behind the scenes — outdated laundry systems.",
      content:
        "Every day, hotels and hospitals lose millions without even noticing. The culprit sits quietly behind the scenes — outdated laundry systems.\n\nHigher water bills, longer cycles, linen damage, and downtime during peak hours all add up to hidden operational losses.",
      category: "Linen hygiene",
      image: "/images/blog-outdated-systems.jpg",
      date: "2025-08-19",
    },
  ],
  about: {
    title: "About Us",
    intro: "Laundrex Laundry Systems Pvt. Ltd. — India's trusted partner for on-premise commercial laundry since 2010.",
    mission: "",
    vision: "",
    heroImage: "/images/hero.jpg",
    missionTitle: "Our Mission",
    visionTitle: "Our Vision",
    journeyTitle: "Our Journey",
    timeline: [
      { year: "2010", title: "Foundation", description: "A visit to a U.S. laundromat sparked Anshul Gupta's vision: India deserved structured, tech-driven laundry too. He shared it with his brother, Ankur Gupta—and together they set out to bring the laundromat revolution to India." },
      { year: "2011", title: "Expansion", description: "The idea caught fire. Laundrex opened 40+ laundromats across India, proving demand for organized, reliable laundry services." },
      { year: "2012", title: "OEM Partnerships", description: "Partnered with Electrolux Professional to introduce energy-efficient, gas-based machines—raising the bar for performance and sustainability in India." },
      { year: "2013", title: "Healthcare & Hospitality", description: "Expanded into hotels and hospitals, delivering professional laundry solutions to leading brands like Marriott and Taj." },
      { year: "2014", title: "Growth", description: "Abhishek Gupta joined to power the next phase of growth and strengthen capital discipline. Signed an agreement with TREVIL to bring premium finishing solutions to India." },
      { year: "2015", title: "Defence", description: "Executed a landmark on-premise laundry for the Indian Military Academy—a showcase of scale, hygiene, and reliability." },
      { year: "2016", title: "LG Partnership", description: "Joined hands with LG Commercial Laundry to revolutionize semi-commercial laundries across India—faster installs, smarter operations, better outcomes." },
      { year: "2018", title: "Experience Center", description: "Opened India's first Laundry Experience Center in New Delhi—educating customers on process, hygiene, and sustainable technology." },
      { year: "2019", title: "Scale", description: "Crossed 350+ employees and 3,000+ machines installed, serving many of India's biggest brands nationwide." },
      { year: "2020", title: "BOO Model", description: "Introduced the Build-Own-Operate (BOO) model—helping 5-star hotels and hospitals run on-premise laundries with zero capex and professional management." },
      { year: "2024", title: "Milestone", description: "Now processing 50,000 kg of linen daily for partners including Marriott, Radisson, and AIIMS—with uptime, quality, and sustainability at the core." },
      { year: "2025", title: "Funding & ReWeave", description: "Raised $6 million from Alkemi Growth Capital and Blue Ashva Capital. Launched ReWeave 360—our circular initiative turning waste into worth." },
    ],
  },
  sustainability: {
    title: "Sustainability",
    intro: "Sustainability is not just a buzzword for us. It's how we design, build, and run every on-premise hotel laundry—lowering your cost per kg while shrinking water, energy, and chemical footprints, with proof you can audit. Impact at a glance: 40% reduction in water usage, 70% reduction in carbon emissions, 450+ million liters of water saved, and ~160 million kg of carbon cut across partner properties.",
    heroImage: "/images/sustainability-water.jpg",
    metrics: [
      { value: 40, suffix: "%", label: "reduction in water usage" },
      { value: 70, suffix: "%", label: "reduction in carbon emissions" },
      { value: 450, suffix: "+ million liters", label: "of water saved" },
      { value: 160, suffix: " million kg", label: "of carbon cut" },
    ],
    initiatives: [],
  },
  team: {
    title: "Our Team",
    intro: "",
    heroImage: "/images/hero.jpg",
    members: [
      { id: "m1", name: "Anshul Gupta", role: "CEO", image: "/images/founder.jpg", bio: "" },
      { id: "m2", name: "Abhishek Gupta", role: "CFO", image: "", bio: "" },
      { id: "m3", name: "Ankur Gupta", role: "CTO", image: "", bio: "" },
      { id: "m4", name: "Anand Dharmadhyaksha", role: "CGO", image: "", bio: "" },
      { id: "m5", name: "Neeti Kalra", role: "General Manager – HR", image: "", bio: "" },
      { id: "m6", name: "Antima Gautam", role: "Sr. Manager - Financial Planning & Analysis", image: "", bio: "" },
      { id: "m7", name: "Dadasaheb Bhagwan S", role: "Sr. Vice President - Engineering & Business", image: "", bio: "" },
      { id: "m8", name: "Manibhadra Sahu", role: "Finance Controller", image: "", bio: "" },
      { id: "m9", name: "Prashant Vaidya", role: "Regional Operational Lead", image: "", bio: "" },
      { id: "m10", name: "Anil Dobhal", role: "Logistics Head", image: "", bio: "" },
      { id: "m11", name: "CD Sharma", role: "Regional Operational Lead", image: "", bio: "" },
    ],
  },
  investors: { title: "Our Investors", intro: "", highlights: [], partners: [] },
  careers: { title: "Careers", intro: "", benefitsTitle: "", benefits: [], openingsTitle: "", openings: [] },
  contact: {
    title: "Contact Us",
    intro: "Call Us or fill the form",
    mapEmbed: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3506.2233913121413!2d77.0899!3d28.4945!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMjjCsDI5JzQwLjIiTiA3N8KwMDUnMjMuNiJF!5e0!3m2!1sen!2sin!4v1600000000000",
  },
  footer: {
    aboutText: "Laundrex Laundry Systems Pvt. Ltd.",
    copyright: "© Laundrex Laundry Systems Pvt. Ltd.",
    solutionsTitle: "Our Solutions",
    companyTitle: "Company",
    headOfficeTitle: "Head Office",
    legalLinks: [
      { label: "Privacy Policy", href: "/legal/privacy" },
      { label: "Terms of Service", href: "/legal/terms" },
      { label: "Code of Conduct", href: "/legal/code-of-conduct" },
    ],
  },
  cookieConsent: {
    message: "We use cookies to ensure that we give you the best experience on our website.",
    acceptText: "Accept",
    declineText: "Decline",
    policyLink: "/legal/privacy",
    policyLabel: "Learn more",
  },
  reweave360: {
    heroTitle: "ReWeave 360",
    heroSubtitle: "India's first circular linen economy programme",
    stats: [
      { value: 33, suffix: "+", label: "Properties Onboarded" },
      { value: 3676, suffix: "+", label: "kg Linen Recycled" },
      { value: 36.7, suffix: "M L", label: "Water Saved" },
    ],
    partnersTitle: "Our Valued Partners",
    wakeUpTitle: "A Wake-Up Call !",
    wakeUpParagraphs: [],
    programTitle: "ReWeave 360",
    programDescription: "ReWeave 360 is India's first circular linen economy program by Laundrex.",
    howItWorksTitle: "How It Works",
    steps: [],
    benefitsTitle: "What Your Brand Gains",
    benefits: [],
    wasteToWorthTitle: "From Waste to Worth",
    wasteToWorthDescription: "",
    getStartedTitle: "Get Started",
    getStartedDescription: "",
    contactPhone: "+91 96672 11788",
    contactEmail: "info@reweave360.com",
    contactWebsite: "www.reweave360.com",
    ctaText: "Partner With Us",
  },
  financialPlanning: { title: "Financial Planning", intro: "", sections: [] },
  legal: {
    privacy: { title: "Privacy Policy", lastUpdated: "2025-01-01", sections: [{ heading: "Privacy Policy", body: "Laundrex Laundry Systems Pvt. Ltd. privacy policy." }] },
    terms: { title: "Terms of Service", lastUpdated: "2025-01-01", sections: [{ heading: "Terms", body: "Laundrex Laundry Systems Pvt. Ltd. terms of service." }] },
    codeOfConduct: { title: "Code of Conduct", lastUpdated: "2025-01-01", sections: [{ heading: "Code of Conduct", body: "Laundrex Laundry Systems Pvt. Ltd. code of conduct." }] },
  },
  contactSubmissions: [],
  newsletterSubmissions: [],
};

fs.writeFileSync(path.join(__dirname, "..", "data", "cms.json"), JSON.stringify(cms, null, 2));
console.log("cms.json seeded");
